### ISSUE TITLE
粗体斜体无法显示

### ISSUE THREAD

**Issue by QYQSDTC** [dongleizhang/AcademicCV#1]
编译出来没有粗体和斜体的区别

**Comment by QYQSDTC** [comment]
好像是没下粗体的palanito😂

**Comment by dongleizhang** [comment]
@QYQSDTC 你需要分别安装Palatino的Regular、Italic、Bold、Bold Italic四种不同的字体。下面图片是我在macOS里装完字体后的的情况。
<img width="203" alt="screen shot 2017-11-10 at 19 41 25" src="https://user-images.githubusercontent.com/19180725/32657038-2afa2192-c64f-11e7-83d1-6b09ff8171ea.png">
